//
//  newsTests-newsMocks.generated.swift
//  news
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import news
import Foundation
import GRDB
import Swift
import SwiftUI
import newsShared

private let mkbGenericStaticMockContext = Mockingbird.GenericStaticMockContext()

// MARK: - Mocked HttpClient
public final class HttpClientMock: news.HttpClient, Mockingbird.Mock {
  typealias MockingbirdSupertype = news.HttpClient
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "news"])

  fileprivate init(sourceLocation: Mockingbird.SourceLocation) {
    self.mockingbirdContext.sourceLocation = sourceLocation
    HttpClientMock.mockingbirdContext.sourceLocation = sourceLocation
  }

  // MARK: Mocked `rawRequest`(`router`: news.HttpRouter, `headers`: [String: String]?, `queryItems`: [URLQueryItem]?, `body`: Data?)
  public func `rawRequest`(`router`: news.HttpRouter, `headers`: [String: String]?, `queryItems`: [URLQueryItem]?, `body`: Data?) async throws -> news.HttpClientResponseRaw {
    return try await self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`rawRequest`(`router`: news.HttpRouter, `headers`: [String: String]?, `queryItems`: [URLQueryItem]?, `body`: Data?) async throws -> news.HttpClientResponseRaw", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`router`), Mockingbird.ArgumentMatcher(`headers`), Mockingbird.ArgumentMatcher(`queryItems`), Mockingbird.ArgumentMatcher(`body`)], returnType: Swift.ObjectIdentifier((news.HttpClientResponseRaw).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (news.HttpRouter, [String: String]?, [URLQueryItem]?, Data?) async throws -> news.HttpClientResponseRaw { return try await mkbImpl(`router`, `headers`, `queryItems`, `body`) }
      if let mkbImpl = mkbImpl as? () async throws -> news.HttpClientResponseRaw { return try await mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: news.HttpClientResponseRaw = try await mkbObject.`rawRequest`(router: `router`, headers: `headers`, queryItems: `queryItems`, body: `body`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (news.HttpClientResponseRaw).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `rawRequest`(`router`: @autoclosure () -> news.HttpRouter, `headers`: @autoclosure () -> [String: String]?, `queryItems`: @autoclosure () -> [URLQueryItem]?, `body`: @autoclosure () -> Data?) async -> Mockingbird.Mockable<Mockingbird.ThrowingAsyncFunctionDeclaration, (news.HttpRouter, [String: String]?, [URLQueryItem]?, Data?) async throws -> news.HttpClientResponseRaw, news.HttpClientResponseRaw> {
    return Mockingbird.Mockable<Mockingbird.ThrowingAsyncFunctionDeclaration, (news.HttpRouter, [String: String]?, [URLQueryItem]?, Data?) async throws -> news.HttpClientResponseRaw, news.HttpClientResponseRaw>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`rawRequest`(`router`: news.HttpRouter, `headers`: [String: String]?, `queryItems`: [URLQueryItem]?, `body`: Data?) async throws -> news.HttpClientResponseRaw", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`router`), Mockingbird.resolve(`headers`), Mockingbird.resolve(`queryItems`), Mockingbird.resolve(`body`)], returnType: Swift.ObjectIdentifier((news.HttpClientResponseRaw).self)))
  }
}

/// Returns a concrete mock of `HttpClient`.
public func mock(_ type: news.HttpClient.Protocol, file: StaticString = #file, line: UInt = #line) -> HttpClientMock {
  return HttpClientMock(sourceLocation: Mockingbird.SourceLocation(file, line))
}

// MARK: - Mocked Repository
public final class RepositoryMock: news.Repository, Mockingbird.Mock {
  typealias MockingbirdSupertype = news.Repository
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "news"])

  fileprivate init(sourceLocation: Mockingbird.SourceLocation) {
    self.mockingbirdContext.sourceLocation = sourceLocation
    RepositoryMock.mockingbirdContext.sourceLocation = sourceLocation
  }

  // MARK: Mocked `getArticles`(`query`: String, `page`: Int)
  public func `getArticles`(`query`: String, `page`: Int) -> AsyncStream<news.Resource<[news.ArticleEntity]>> {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`getArticles`(`query`: String, `page`: Int) -> AsyncStream<news.Resource<[news.ArticleEntity]>>", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`query`), Mockingbird.ArgumentMatcher(`page`)], returnType: Swift.ObjectIdentifier((AsyncStream<news.Resource<[news.ArticleEntity]>>).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (String, Int) -> AsyncStream<news.Resource<[news.ArticleEntity]>> { return mkbImpl(`query`, `page`) }
      if let mkbImpl = mkbImpl as? () -> AsyncStream<news.Resource<[news.ArticleEntity]>> { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: AsyncStream<news.Resource<[news.ArticleEntity]>> = mkbObject.`getArticles`(query: `query`, page: `page`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (AsyncStream<news.Resource<[news.ArticleEntity]>>).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `getArticles`(`query`: @autoclosure () -> String, `page`: @autoclosure () -> Int) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String, Int) -> AsyncStream<news.Resource<[news.ArticleEntity]>>, AsyncStream<news.Resource<[news.ArticleEntity]>>> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String, Int) -> AsyncStream<news.Resource<[news.ArticleEntity]>>, AsyncStream<news.Resource<[news.ArticleEntity]>>>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`getArticles`(`query`: String, `page`: Int) -> AsyncStream<news.Resource<[news.ArticleEntity]>>", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`query`), Mockingbird.resolve(`page`)], returnType: Swift.ObjectIdentifier((AsyncStream<news.Resource<[news.ArticleEntity]>>).self)))
  }

  // MARK: Mocked `getArticles`(`query`: String, `page`: Int, `refresh`: Bool)
  public func `getArticles`(`query`: String, `page`: Int, `refresh`: Bool) -> AsyncStream<news.Resource<[news.ArticleEntity]>> {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`getArticles`(`query`: String, `page`: Int, `refresh`: Bool) -> AsyncStream<news.Resource<[news.ArticleEntity]>>", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`query`), Mockingbird.ArgumentMatcher(`page`), Mockingbird.ArgumentMatcher(`refresh`)], returnType: Swift.ObjectIdentifier((AsyncStream<news.Resource<[news.ArticleEntity]>>).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (String, Int, Bool) -> AsyncStream<news.Resource<[news.ArticleEntity]>> { return mkbImpl(`query`, `page`, `refresh`) }
      if let mkbImpl = mkbImpl as? () -> AsyncStream<news.Resource<[news.ArticleEntity]>> { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: AsyncStream<news.Resource<[news.ArticleEntity]>> = mkbObject.`getArticles`(query: `query`, page: `page`, refresh: `refresh`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (AsyncStream<news.Resource<[news.ArticleEntity]>>).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `getArticles`(`query`: @autoclosure () -> String, `page`: @autoclosure () -> Int, `refresh`: @autoclosure () -> Bool) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String, Int, Bool) -> AsyncStream<news.Resource<[news.ArticleEntity]>>, AsyncStream<news.Resource<[news.ArticleEntity]>>> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String, Int, Bool) -> AsyncStream<news.Resource<[news.ArticleEntity]>>, AsyncStream<news.Resource<[news.ArticleEntity]>>>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`getArticles`(`query`: String, `page`: Int, `refresh`: Bool) -> AsyncStream<news.Resource<[news.ArticleEntity]>>", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`query`), Mockingbird.resolve(`page`), Mockingbird.resolve(`refresh`)], returnType: Swift.ObjectIdentifier((AsyncStream<news.Resource<[news.ArticleEntity]>>).self)))
  }
}

/// Returns a concrete mock of `Repository`.
public func mock(_ type: news.Repository.Protocol, file: StaticString = #file, line: UInt = #line) -> RepositoryMock {
  return RepositoryMock(sourceLocation: Mockingbird.SourceLocation(file, line))
}
